# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 22:40:52 by jaleman           #+#    #+#              #
#    Updated: 2018/11/06 22:40:53 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Sources:
# https://vidhyachari.wordpress.com/2017/09/01/setting-up-gogs-on-docker/
# https://github.com/rosstimson/docker-gogs

#------------------------------------------------------------------------------#
# Design a Dockerfile that gets the development version of Gogs, installs it
# with all the dependencies and the necessary configurations, and launches the
# application, all as it builds. The container will be deemed valid if you can
# access the web client, and if you can interact via GIT with this container.
# Test(s):
# ```
#   > docker build -t gogs .
#   > docker run --detach --name Gogs --publish 3000:3000 gogs
#   > docker run -it gogs
# ```
#------------------------------------------------------------------------------#
