#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    00                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#------------------------------------------------------------------------------#
# Install all the dependencies. ;)
#------------------------------------------------------------------------------#

# Check if the user uses a Mac.
if [ $(uname -s) = "Darwin" ] ; then
    # Update packages
    echo " > Updating / installing dependencies..." ;
    brew update &>/dev/null ;
    echo "...this might take a few seconds" ;
    # Install packages only if they don't exist
    for pkg in docker docker-machine shc ; do
        if brew list -1 | grep -q "^${pkg}\$"; then
            echo "Package '$pkg' is installed" ;
        else
            echo "Installing package $pkg" ;
            brew install $pkg &>/dev/null ;
        fi
    done
    brew cask install virtualbox &>/dev/null ;
    echo "Done."
fi

exit ;
