#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    00                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#------------------------------------------------------------------------------#
# 0. Install all the dependencies. ;)
#------------------------------------------------------------------------------#

# Check if the user uses a Mac.
if [ $(uname -s) = "Darwin" ] ; then
    echo " > Updating / installing dependencies..."
    brew update
    brew install docker
    brew install docker-machine
    brew cask install virtualbox;
    brew install shc
fi
