#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    03                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;

#------------------------------------------------------------------------------#
# Define the variables needed by your virtual machine Char in the general env
# of your terminal, so that you can run the docker ps command without errors.
#------------------------------------------------------------------------------#

# Define the variables of the VM in the general env of the terminal.
ENV_VAR=$(docker-machine env "$VM_NAME") ;
eval $ENV_VAR ;
echo "Variables defined" ;

export ENV_VAR ;
exit ;
