#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    06                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Launch an nginx container, available on Docker Hub, as a background task.
# It should be named overlord, be able to restart on its own, and have its
# 80 port attached to the 5000 port of Char.
# You can check that your container functions properly by visiting
# http://<ip-de-char>:5000 on your web browser.
#------------------------------------------------------------------------------#

# Gets the nginx container.
docker pull nginx ;

# Runs the container in the background (detached).
SERVER_ID=$(docker run --detach \
                       --name $SERVER_NAME \
                       --publish $VM_IP:$SERVER_PORT:80 \
                       --restart=always nginx) ;

export SERVER_ID ;
exit ;
