#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    07                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "_vars" ;

#------------------------------------------------------------------------------#
# Get the internal IP address of the overlord container without starting its
# shell and in one command.
#------------------------------------------------------------------------------#

# Get internal IP address of the container
CONTAINER_IP=$(docker inspect --format \
        '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID) ;
echo $CONTAINER_IP ;

export CONTAINER_IP ;
exit ;
