#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    07                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Get the internal IP address of the overlord container without starting its
# shell and in one command.
#------------------------------------------------------------------------------#

SERVER_ID=$(docker run --detach \
                       --name $SERVER_NAME \
                       --publish $VM_IP:$SERVER_PORT:80 \
                       --restart=always nginx) ;

# Get internal IP address of the container
SERVER_IP=$(docker inspect --format \
        '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $SERVER_ID) ;
echo $SERVER_IP ;

export SERVER_IP ;
exit ;
