#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    13                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Print the environment variables of the spawning-pool container in one
# command, to be sure that you have configured your container properly.
#------------------------------------------------------------------------------#

# Print the enviroment variables of the container.
docker inspect --format='{{.Config.Env}}' $DATABASE_CONTAINER ;

exit ;
