#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    19                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "_vars" ;


#------------------------------------------------------------------------------#
# Python container, 2-slim version, its /root folder will be bound to a
# HOME folder on your host, and its 3000 port will be bound to the 3000 port
# of your virtual machine.
# You will personalize this container so that you can use the Flask
# micro-framework in its latest version. You will make sure that an html
# page displaying "Hello World" with <h1> tags can be served by Flask.
# You will test that your container is properly set up by accessing,
# via curl or a web browser, the IP address of your virtual machine on the\
# 3000 port.
# You will also list all the necessary commands in your repository.
# ---
#   docker-machine ssh $VM_NAME "cd /home && mkdir $FLASK_CONTAINER"
#   docker-machine scp ../resources/app.py Char:/home/$FLASK_CONTAINER
#------------------------------------------------------------------------------#

# Directory to be bound from the /root directory of the python container.
mkdir $HOME/root ;

# Pulls the python container
docker pull python ;

# Launch a flash (python) container, with a lot of crazy personalized stuff.
FLASK_ID=$(docker run -dt --name $FLASK_CONTAINER \
                          --volume $HOME/root:/root \
                          --publish $FLASK_PORT:3000 \
                          python:2-slim \
                          bash -c 'pip install flask && python /root/app.py') ;

export FLASK_ID ;
exit ;
