#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    20                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Create a local swarm, the Char virtual machine should be its manager.
#------------------------------------------------------------------------------#

# Create a local swarm.
# More about swarms: https://www.youtube.com/watch?v=KC4Ad1DS8xU
docker swarm init --advertise-addr $VM_IP ;
