#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    23                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Create an overlay-type internal network that you will name overmind.
#------------------------------------------------------------------------------#

# Create an overlay internal network.
docker network create --internal --driver overlay $OVERLAY_NETWORK ;

exit ;
