#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    26                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Launch a 42school/engineering-bay service in two replicas.
# This service will be named engineering-bay and
# will be on the overmind network.
#------------------------------------------------------------------------------#

# Launch a service in two replicas.
docker service create --name $SERVICE_NAME2 \
                      --network $OVERLAY_NETWORK \
                      -e OC_DEFAULT_USER=$SERVICE_USER \
                      -e OC_DEFAULT_PASS=$SERVICE_PASS \
                      --replicas 2 \
                      42school/$SERVICE_NAME2

exit ;
