#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    27                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "_vars" ;

#------------------------------------------------------------------------------#
# Get the real-time logs of one the tasks of the engineering-bay service.
#------------------------------------------------------------------------------#

# echo $SERVICE_NAME2

# Get the real-time logs.
docker service logs --follow `docker service ps --filter "name=$SERVICE_NAME2.2" $SERVICE_NAME2 --quiet | head -1`
