#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    27                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "_vars" ;

#------------------------------------------------------------------------------#
# Get the real-time logs of one the tasks of the engineering-bay service.
#------------------------------------------------------------------------------#

# Get the service ids
SERVICE_ID=$(docker service ps -f name=engineering-bay.1 engineering-bay -q)

# Get the real-time logs.
docker service logs -f "$($SERVICE_ID | head -n1 | cut -d " " -f1)"
