#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    27                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Get the real-time logs of one the tasks of the engineering-bay service.
#------------------------------------------------------------------------------#

# Get the real-time logs.
docker service logs --follow `docker service ps \
                              --filter "name=engineering-bay.2" $SERVICE_NAME2 \
                              --quiet` ;

exit ;
