#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    30                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source "./_vars" ;
eval $ENV_VAR ;

#------------------------------------------------------------------------------#
# Increase the number of copies of the marines service up to twenty,
# because there’s never enough Marines to eliminate Zergs.
# (Remember to take a look at the tasks and logs of the servic you’ll see)
#------------------------------------------------------------------------------#

# Increase the number of copies in a service.
docker service scale $SERVICE_NAME3=20 ;

exit ;
