#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    _vars                                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/03 03:29:50 by jaleman           #+#    #+#              #
#    Updated: 2017/08/03 03:29:58 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Declare variables
declare VM_IP ;
declare CONTAINER_ID ;
declare CONTAINER_IP ;
declare DATABASE_ID ;
declare WORDPRESS_ID ;
declare PHPMYADMIN_ID ;
declare FLASK_ID ;
declare SWARM_TOKEN ;
declare ENV_VAR ;

# Export variables
export VM_NAME="Char" ;
export VM_NAME2="Aiur" ;
export CONTAINER_NAME="overlord" ;
export CONTAINER_PORT="5000" ;
export VOLUME_NAME="hatchery" ;
export DATABASE_NAME="zerglings" ;
export DATABASE_PASS="Kerrigan" ;
export DATABASE_CONTAINER="spawning-pool" ;
export WORDPRESS_CONTAINER="lair" ;
export WORDPRESS_PORT="8080" ;
export PHPMYADMIN_PORT="8081" ;
export PHPMYADMIN_NAME="roach-warden" ;
export FLASK_CONTAINER="Abathur" ;
export FLASK_PATH="~/root" ;
export FLASK_PORT="3000" ;
export SWARM_PORT="2377" ;
export OVERLAY_NETWORK="overmind" ;
export SERVICE_NAME="orbital-command" ;
export SERVICE_USER="orbital-command" ;
export SERVICE_PASS="orbital-command" ;
export SERVICE_NAME2="engineering-bay" ;
export SERVICE_NAME3="marine-squad" ;
export ENV_VAR=$(docker-machine env "$VM_NAME") ;
